### ISSUE TITLE
Loadpath configuration not doable without adb ?

### ISSUE THREAD

**Issue by ghost** [YasuakiHonda/Maxima-on-Android#10]
Been on a longer vacation without a computer recently and played with maxima. It worked quite nicely but I could not figure out any way to make editing and loading source files reasonable painless. 

Tried a bunch of things but session management did not work as I would naively expect, trying to create a local configuration file with maxima failed.

Would it be possible to look for /sdcard/maxima/maximia-init.mc ?

**Comment by YasuakiHonda** [comment]
I will consider to add path where 3rd party editors can create files for maxima-init.mac. One consideration is the security, though. Any app could create maxima-init.mac with bad commands and when you start MoA without noticing that fact, MoA behaves unexpectedly...

**Comment by rgh36167** [comment]
yes, it is a security issue but an evil app that can write to SD card will probably find much easier ways to achieve its evil goals than by manipulating maxima. The only extra permission it could get by manipulating maxima is INTERNET. . chances are rather small that an evil app would not have this permission already.

What are the alternatives - any possibility to read maxima files from SD has the same security issue. Are there possibilities to make maxima files editable by 3rd party editors without saving them to SD perhaps by passing them as intent? Or would porting some small lisp editor to maxima?

Personally I just use trusted ope source apps from f-droid.org, except for a few prepackaged apps.
